### ISSUE TITLE
Handle the decision of name >> id >> "unknown" better

### ISSUE THREAD

**Issue by ddieruf** [LangStream/vscode-extension#21]
An object could have a name, an id, or be unknown. Any of those could be undefined, null, or empty string. Handle it all

```
pipelines:
    - id: pipeline
      module: default
      name: null
```
